### ISSUE TITLE
Leaf nodes don't have active status

### ISSUE THREAD

**Issue by adamlc** [goliatone/gmenu#2]
I was just wondering why leaf nodes don't have an active status? For example

```
/test
/test/123
```

When I'm at page ```/test/123``` then ```/test``` will have an active status. But when I'm at ```/test``` it doesn't have an active status.

Just wondering if there is a reason for this or if its a bug?

**Comment by goliatone** [comment]
@adamlc Thanks for reporting this behavior. I will look into it to figure out what's happening, but it sounds like a bug.

**Comment by adamlc** [comment]
@goliatone any ideas? It seems simply removing the check if its a leaf node seems to work :)
